// <auto-generated />
using System;
using ControllerFirst.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControllerFirst.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20250424112512_Fourth")]
    partial class Fourth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControllerFirst.Data.Models.Role", b =>
                {
                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roleName");

                    b.HasKey("RoleName")
                        .HasName("PK__Roles__B19478603A776CCC");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<bool>("IsEmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isEmailConfirmed");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("refreshToken");

                    b.Property<DateTime>("RefreshTokenExpiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("refreshTokenExpiration");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshToken");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E61646FB653B8")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ__Users__C927F7B4D6A3D3A3")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CVVEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CardNumberEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCard");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userRoleId");

                    b.Property<string>("RoleNameRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("roleNameRef");

                    b.Property<Guid>("UserRef")
                        .HasMaxLength(50)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userRef");

                    b.HasKey("UserRoleId")
                        .HasName("PK__UserRole__CD3149CCDE4D7241");

                    b.HasIndex("RoleNameRef");

                    b.HasIndex("UserRef");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserAddress", b =>
                {
                    b.HasOne("ControllerFirst.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserCard", b =>
                {
                    b.HasOne("ControllerFirst.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.UserRole", b =>
                {
                    b.HasOne("ControllerFirst.Data.Models.Role", "RoleNameRefNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleNameRef")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__roleN__2B3F6F97");

                    b.HasOne("ControllerFirst.Data.Models.User", "UserNameRefNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserRef")
                        .IsRequired()
                        .HasConstraintName("FK__UserRoles__userN__2A4B4B5E");

                    b.Navigation("RoleNameRefNavigation");

                    b.Navigation("UserNameRefNavigation");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ControllerFirst.Data.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
